### ISSUE TITLE
Zbieranie raportów

### ISSUE THREAD

**Issue by rswc** [rswc/bem#29]
Po wykonaniu taska Node powinien przesłać do koordynatora wyniki.

Trzeba się tu zastanowić:
 - co ma być zawarte w raporcie
 - co się dzieje z otrzymanymi raportami po stronie koordynatora
 - jak raporty mają być agregowane

W opisie projektu chyba obiecaliśmy live-aktualizowane statystyki, więc dobrze by było coś takiego mieć.

**Comment by pavveu7** [comment]
Myślę, że biorąc pod uwagę czas jaki został, dobrze byłoby się skupić na zapewnieniu wyników dla pojedynczych "Tasków" (#35). W takiej sytuacji wystarczy się ograniczyć dla zmiennych `win_agent1` i `win_agent2` (zakładając pojedynki po `<games>` gier). Będzie to szybkie w implementacji a można przedstawiać jako procentową "dominację" jednego z graczy nad drugim.
