### ISSUE TITLE
Przechwytywanie błędów przy uruchamianiu gry na nodzie

### ISSUE THREAD

**Issue by rswc** [rswc/bem#36]
Obecnie, kiedy node próbuje uruchomić taska i to nie wyjdzie (np. nie ma zainstalowanej javy), liczy taki mecz jako draw.

Powinno być to jakoś przechwytywane, raportowane i wyświetlane na koordynatorze.

**Comment by pavveu7** [comment]
Myślę że dobrze byłoby explicite liczyć coś w stylu "failed games" (w `Result`)? Bo w sytuacji jak np jedna gra się nie uda z 1000, to słabo byłoby np zwracać "TASK_FAILED". Ale jak najbardziej trzeba to poprawnie przechwytywać
