### ISSUE TITLE
CodeReview changes

### ISSUE THREAD

**Issue by pavveu7** [rswc/bem#7]
## Opinia

Poniżej znajduje się komentarz dotyczący code-review od prowadzącego. 

### Ogólna 

> Kody czytelny i wygląda dobrze. Podział na wątki i obsługa sieci OK. Przy odbieraniu wiadomości musicie dodać obsługę sklejenia się kilku wiadomości. Na razie nie widzę samego przesyłania treści zadania, uruchamiania zadań i logiki z tym związanej. 

Oczywistym dalszym krokiem będzie implementacja logiki, po dodaniu wszystkich poprawek wskazanych przez prowadzącego.  

### Graceful-Exit 

Dokładne informacje przeniesione do nowego Issue, który agreguje ptrzebne zmiany aby to zaimplementować

- [x] #4

## Wskazane Poprawki

Poniżej wskazane poprawki do wykonania. 
>  Przy niektórych punktach umieszczałem oznaczenia:
[.] – nie ma wpływu na ocenę, wskazuję na "dobre praktyki" albo jak wydajniej napisać kod
[?] – nie rozumiem dlaczego tak
[ ] - błąd lub coś co wymaga poprawienia
[!] – duży lub oczywisty błąd

Aby upewnić się, że wszystko będzie pokryte, wszystkie zostały przerzucone jako Issue. W momencie poprawiania wystarczy "closes +nr" i powinno samo się pozamykać.

### common 

- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18 

### node

- [x] #19
- [x] #20
- [x] #21 

### coordinator

- [x] #22
- [x] #23

**Comment by rswc** [comment]
![man](https://user-images.githubusercontent.com/48861946/210139790-c48fa6fc-021d-40a7-9909-2588b80c6c90.png)
